-- Insertar categorías
INSERT INTO public.categories (id, title, slug, img_src, alt, description)
VALUES
	(1, 'Polos', 'polos', '/images/polos.jpg', 'Hombre luciendo polo azul', 'Polos exclusivos con diseños que todo desarrollador querrá lucir. Ideales para llevar el código a donde vayas.'),
	(2, 'Tazas', 'tazas', '/images/tazas.jpg', 'Tazas con diseño de código', 'Tazas que combinan perfectamente con tu café matutino y tu pasión por la programación.'),
	(3, 'Stickers', 'stickers', '/images/stickers.jpg', 'Stickers de desarrollo web', 'Personaliza tu espacio de trabajo con nuestros stickers únicos y muestra tu amor por el desarrollo web.');

-- Insertar productos
INSERT INTO public.products (id, title, img_src, price, description, category_id, features)
VALUES
	(1, 'Polo React', '/images/polos/polo-react.png', 2000, 'Viste tu pasión por React con estilo y comodidad en cada línea de código.', 1, '["Estampado resistente que mantiene sus colores vibrantes lavado tras lavado.", "Hecho de algodón suave que asegura comodidad y frescura.", "Costuras reforzadas para una mayor durabilidad.", "Corte moderno que se adapta perfectamente al cuerpo."]'::jsonb),
	(2, 'Polo JavaScript', '/images/polos/polo-js.png', 2000, 'Deja que tu amor por JavaScript hable a través de cada hilo de este polo.', 1, '["Logo de JavaScript bordado con precisión y detalle.", "Tela premium de algodón peinado.", "Disponible en varios colores.", "Acabado profesional con doble costura."]'::jsonb),
	(3, 'Polo Node.js', '/images/polos/polo-node.png', 2000, 'Conéctate al estilo con este polo de Node.js, tan robusto como tu código.', 1, '["Diseño minimalista con el logo de Node.js.", "Material transpirable ideal para largas sesiones de código.", "Tejido resistente a múltiples lavados.", "Etiqueta sin costuras para mayor comodidad."]'::jsonb),
	(4, 'Polo TypeScript', '/images/polos/polo-ts.png', 2000, 'Tipa tu estilo con precisión: lleva tu pasión por TypeScript en cada hilo.', 1, '["Logo de TypeScript estampado en alta calidad.", "Tejido antimanchas y duradero.", "Cuello reforzado que mantiene su forma.", "100% algodón hipoalergénico."]'::jsonb),
	(5, 'Polo Backend Developer', '/images/polos/polo-backend.png', 2500, 'Domina el servidor con estilo: viste con orgullo tu título de Backend Developer.', 1, '["Diseño exclusivo para desarrolladores backend.", "Material premium que mantiene su forma.", "Costuras reforzadas en puntos de tensión.", "Estampado de alta durabilidad."]'::jsonb),
	(6, 'Polo Frontend Developer', '/images/polos/polo-frontend.png', 2500, 'Construye experiencias con estilo: luce con orgullo tu polo de Frontend Developer.', 1, '["Diseño inspirado en elementos de UI/UX.", "Tela suave y ligera perfecta para el día a día.", "Estampado flexible que no se agrieta.", "Acabado profesional en cada detalle."]'::jsonb),
	(7, 'Polo Full-Stack Developer', '/images/polos/polo-fullstack.png', 2500, 'Domina ambos mundos con estilo: lleva tu título de FullStack Developer en cada línea de tu look.', 1, '["Diseño que representa ambos mundos del desarrollo.", "Material premium de larga duración.", "Proceso de estampado ecológico.", "Corte moderno y cómodo."]'::jsonb),
	(8, 'Polo It''s A Feature', '/images/polos/polo-feature.png', 1500, 'Cuando el bug se convierte en arte: lleva con orgullo tu polo ''It''s a feature''.', 1, '["Estampado humorístico de alta calidad.", "Algodón orgánico certificado.", "Diseño exclusivo de la comunidad dev.", "Disponible en múltiples colores."]'::jsonb),
	(9, 'Polo It Works On My Machine', '/images/polos/polo-works.png', 1500, 'El clásico del desarrollador: presume tu confianza con ''It works on my machine''.', 1, '["Frase icónica del mundo del desarrollo.", "Material durable y cómodo.", "Estampado que no se desvanece.", "Ideal para regalo entre desarrolladores."]'::jsonb),
	(10, 'Sticker JavaScript', '/images/stickers/sticker-js.png', 299, 'Muestra tu amor por JavaScript con este elegante sticker clásico.', 3, '["Vinilo de alta calidad resistente al agua", "Adhesivo duradero que no deja residuos", "Colores vibrantes que no se desvanecen", "Tamaño perfecto para laptops y dispositivos"]'::jsonb),
	(11, 'Sticker React', '/images/stickers/sticker-react.png', 249, 'Decora tus dispositivos con el icónico átomo giratorio de React.', 3, '["Vinilo de alta calidad resistente al agua", "Adhesivo duradero que no deja residuos", "Colores vibrantes que no se desvanecen", "Tamaño perfecto para laptops y dispositivos"]'::jsonb),
	(12, 'Sticker Git', '/images/stickers/sticker-git.png', 399, 'Visualiza el poder del control de versiones con este sticker de Git.', 3, '["Vinilo de alta calidad resistente al agua", "Adhesivo duradero que no deja residuos", "Colores vibrantes que no se desvanecen", "Tamaño perfecto para laptops y dispositivos"]'::jsonb),
	(13, 'Sticker Docker', '/images/stickers/sticker-docker.png', 299, 'La adorable ballena de Docker llevando contenedores en un sticker único.', 3, '["Vinilo de alta calidad resistente al agua", "Adhesivo duradero que no deja residuos", "Colores vibrantes que no se desvanecen", "Tamaño perfecto para laptops y dispositivos"]'::jsonb),
	(14, 'Sticker Linux', '/images/stickers/sticker-linux.png', 249, 'El querido pingüino Tux, mascota oficial de Linux, en formato sticker.', 3, '["Vinilo de alta calidad resistente al agua", "Adhesivo duradero que no deja residuos", "Colores vibrantes que no se desvanecen", "Tamaño perfecto para laptops y dispositivos"]'::jsonb),
	(15, 'Sticker VS Code', '/images/stickers/sticker-vscode.png', 249, 'El elegante logo del editor favorito de los desarrolladores.', 3, '["Vinilo de alta calidad resistente al agua", "Adhesivo duradero que no deja residuos", "Colores vibrantes que no se desvanecen", "Tamaño perfecto para laptops y dispositivos"]'::jsonb),
	(16, 'Sticker GitHub', '/images/stickers/sticker-github.png', 299, 'El alojamiento de repositorios más popular en un sticker de alta calidad.', 3, '["Vinilo de alta calidad resistente al agua", "Adhesivo duradero que no deja residuos", "Colores vibrantes que no se desvanecen", "Tamaño perfecto para laptops y dispositivos"]'::jsonb),
	(17, 'Sticker HTML', '/images/stickers/sticker-html.png', 299, 'El escudo naranja de HTML5, el lenguaje que estructura la web.', 3, '["Vinilo de alta calidad resistente al agua", "Adhesivo duradero que no deja residuos", "Colores vibrantes que no se desvanecen", "Tamaño perfecto para laptops y dispositivos"]'::jsonb),
	(18, 'Taza JavaScript', '/images/tazas/taza-js.png', 1499, 'Disfruta tu café mientras programas con el logo de JavaScript.', 2, '["Cerámica de alta calidad", "Apta para microondas y lavavajillas", "Capacidad de 325ml", "Diseño que no pierde color con el uso"]'::jsonb),
	(19, 'Taza React', '/images/tazas/taza-react.png', 1399, 'Una taza que hace render de tu bebida favorita con estilo React.', 2, '["Cerámica de alta calidad", "Apta para microondas y lavavajillas", "Capacidad de 325ml", "Diseño que no pierde color con el uso"]'::jsonb),
	(20, 'Taza Git', '/images/tazas/taza-git.png', 1299, 'Commit a tu rutina diaria de café con esta taza de Git.', 2, '["Cerámica de alta calidad", "Apta para microondas y lavavajillas", "Capacidad de 325ml", "Diseño que no pierde color con el uso"]'::jsonb),
	(21, 'Taza SQL', '/images/tazas/taza-sql.png', 1599, 'Tu amor por los lenguajes estructurados en una taza de SQL.', 2, '["Cerámica de alta calidad", "Apta para microondas y lavavajillas", "Capacidad de 325ml", "Diseño que no pierde color con el uso"]'::jsonb),
	(22, 'Taza Linux', '/images/tazas/taza-linux.png', 1399, 'Toma tu café con la libertad que solo Linux puede ofrecer.', 2, '["Cerámica de alta calidad", "Apta para microondas y lavavajillas", "Capacidad de 325ml", "Diseño que no pierde color con el uso"]'::jsonb),
	(23, 'Taza GitHub', '/images/tazas/taza-github.png', 1499, 'Colabora con tu café en esta taza con el logo de GitHub.', 2, '["Cerámica de alta calidad", "Apta para microondas y lavavajillas", "Capacidad de 325ml", "Diseño que no pierde color con el uso"]'::jsonb);

-- Actualizar secuencias de IDs para evitar conflictos en inserts futuros
SELECT setval('public.categories_id_seq', (SELECT MAX(id) FROM public.categories));
SELECT setval('public.products_id_seq', (SELECT MAX(id) FROM public.products));